yes_index:
    path:     /
    defaults: { _controller: "AppBundle:Admin:index" }
    methods:  GET

yes_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin:show" }
    methods:  GET

yes_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin:new" }
    methods:  [GET, POST]

yes_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin:edit" }
    methods:  [GET, POST]

yes_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin:delete" }
    methods:  DELETE
